[package]
name = "dma-accessible"
version = "0.1.0"
edition = "2024"

[dependencies]
grounded = "0.2.0"

[dev-dependencies]
panic-halt = "1.0.0"
cortex-m-rt = "0.7"

[[example]]
name = "basic"
path = "examples/basic.rs"